### ISSUE TITLE
"sapi5.1 patch" directory

### ISSUE THREAD

**Issue by gsaponaro** [robotology/speech#12]
Hi @pattacini, I noticed there is a directory called "sapi5.1 patch" in this repository, which from a quick search is not being used or applied anywhere. The ```speechRecognizer``` module is relying on the Microsoft Speech API (SAPI) stuff, but it is not using that patch. Perhaps it's there by mistake?

**Comment by pattacini** [comment]
I think there was not mistake: actually @stephane-lallee might know the reason.

##### PS
I'm not a `speech` developer; I'm just giving support for keeping the repo in good shape :smirk:

**Comment by Tobias-Fischer** [comment]
Wait a minute before deleting anything. This is needed in order to compile the speechRecognizer with the Microsoft speech API 5.1, which is still in use in some labs. Thus, this directory is there for a reason. Please do not delete!

**Comment by pattacini** [comment]
Don't worry @Tobias-Fischer 
I didn't have the intention :smirk:

**Comment by gsaponaro** [comment]
Sorry everyone! I did not intend to cause trouble or worries :)

I am not a developer in this repo (although we use it for POETICON++ which in turn relies on IOL), I was just inquiring because the directory in the topic of this issue caught the attention of my eye (because of the space).

The reason why I thought (I could be wrong) that the "sapi5.1 patch" directory could be redundant was: 1) I did a search on the GitHub interface here, and it looks like the patched file "sphelper.h" within that directory is not being applied or called anywhere, neither from CMake nor from C++ files, see
https://github.com/robotology/speech/search?q=sphelper.h 2) as a result I thought that the changes within that file have already been merged in upstream SAPI, making the patched file redudant.

Sorry again, of course let's not delete anything "just because", and I'm curious to hear what people in the know will say (@stephane-lallee @maxime-petit @gregoire-pointeau).

**Comment by pattacini** [comment]
I think we can close this issue by now.
Any further comment is more than welcome.

**Comment by stephane-lallee** [comment]
Hi !

Yes, I remember creating this.
I think when downloading SAPI (which is now shipped by default with the
newer versions of Windows under the name Speech Platform) there was a need
to manually fix some errors. So I created those files to fix those errors.

Those files were relevant on Windows XP, but I think they are useless with
the current versions of Windows. I would strongly recommend the labs
running on XP to upgrade a more up to date version of Windows ;-)

I pretty sure it is safe to remove this directory, but this should be
double-checked with the different labs which are actively using it.

More generally for the speech recognition topic, I would suggest to start
exploring a more modern solution (e.g. an android phone + 4G card + cloud
based recognition (speech to text) ). But it is another story...

Stéphane
2016-04-11 16:44 GMT+08:00 Ugo Pattacini <notifications@github.com>:

**Comment by pattacini** [comment]
Thanks @stephane-lallee for you insights. And yes, we're already exploring those new solutions you mentioned (cc @vtikha), which are actually way better.

So guys, what should we do with this directory then? 
cc @Tobias-Fischer @robotology/wysiwyd-developers @maxime-petit @gregoire-pointeau

**Comment by pattacini** [comment]
I think no one is still using Windows XP, is that right?

**Comment by Tobias-Fischer** [comment]
Hi guys,
I had a quick chat with @maxime-petit, and he reckons we still need this patch. It is not related to the OS used (we have Windows 7 on our speech recognizer system), but rather to the version of the speech recognizer one downloads.
I am not sure whether newer versions of the MS speech recognizer work with the code in this repo. However, I do remember that I recently needed those files in order to compile our `speechRecognizer`. Thus, I don't think it's safe to delete the directory, and would rather keep it around for some longer.

Best, Tobi

**Comment by pattacini** [comment]
All right, let's close this long debate :smirk:

**Comment by stephane-lallee** [comment]
I'd suggest to try compiling speechRecognizer without downloading any SAPI
on windows 7. I believe all the required SDK should already be there... But
anyway, doesn't hurt to keep the files there, sure ;-)

Stéphane Lallée

*-----------------------------------------------------*
A*Star Scientist
Institute for Infocomm Research - I²R <http://www.i2r.a-star.edu.sg/>

*Fusionopolis, Tower South 10#104**Singapore*
*(+65) 6408 2074*
stephane-l@i2r.a-star.edug.sg
*------------------------------------------------------*

2016-04-11 18:06 GMT+08:00 Ugo Pattacini <notifications@github.com>:
