### ISSUE TITLE
[iSpeak] switch language/voice through rpc (festival)

### ISSUE THREAD

**Issue by jgvictores** [robotology/speech#13]
In iSpeak (using festival), is there any way to switch language/voice through rpc?
In `festival` you can `get` a list, then `set` one:
```
festival> (voice.list)
(kal_diphone JuntaDeAndalucia_es_pa_diphone)
festival> (voice_kal_diphone)      
kal_diphone
```

Thanks!

**Comment by pattacini** [comment]
Hi @jgvictores 
Nope, I don't think so.
Consider that `festival` is about to be deprecated in favor of more recent packages.
You could add this feature yourself and open a PR.

**Comment by jgvictores** [comment]
Hi @pattacini 
Could you point me to a more recent package, for which it this functionality has already been implemented?

**Comment by pattacini** [comment]
Sure, have a look at this recent PR: https://github.com/robotology/speech/pull/11.

**Comment by pattacini** [comment]
More on this: https://github.com/robotology/speech/tree/master/svox-speech.

**Comment by jgvictores** [comment]
Thanks!
Will check out https://github.com/robotology/speech/tree/master/svox-speech !!
