### ISSUE TITLE
Low quality of svox

### ISSUE THREAD

**Issue by amaroyo** [robotology/speech#14]
Hello, 

I am testing the svox speech and I have problems with the understanding of the sentences pronounced by svox. I realized that it's sending the wav files in 16000 Hz quality, is there a way to improve it to, let's say 48000 Hz? 

Thanks, 
Alex.

**Comment by pattacini** [comment]
Hi @amaroyo, 

We are not the maintainer of the svox package, therefore you have to investigate on your own this functionality 😉 

This should be a good starting hint: [**`PICODSP_SAMP_FREQ`**][1].

[1]: https://github.com/robotology/speech/blob/master/svox-speech/svoxpico/picodsp.h#L69

**Comment by amaroyo** [comment]
Hi @pattacini, 

I just found you use [**```SAMPLE_FREQ_16KHZ```**](https://github.com/robotology/speech/blob/master/svox-speech/speech.cpp#L356) as well. I suppose I should change them as well.

Thank you for the hint!
Alex.

**Comment by pattacini** [comment]
I didn't know there was that specific call in the wrapper too (I'm not the developer, actually): I've just searched for `16000` in the code.

As a result, it might be sufficient then to fiddle with only this latter quantity 👍

**Comment by amaroyo** [comment]
Perfect! I will give it a try and tell you if I can manage to improve the quality.

**Comment by amaroyo** [comment]
So, after a year (hehe) I am reopening this issue... I am also adding @reafrancesco and @gonzalezJohnas. So far, I have discovered the following pieces of code that are related to the sampling frequency, only in these two files it is defined the sampling frequency. 

[```#define PICODSP_SAMP_FREQ 16000```](https://github.com/robotology/speech/blob/master/svox-speech/svoxpico/picodsp.h#L69)

[```#define SAMPLE_FREQ_16KHZ (picoos_uint32) 16000```](https://github.com/robotology/speech/blob/master/svox-speech/svoxpico/picoos.h#L360)

In the following files, it's only defined the naming:
[```(picoos_char *) filename.c_str(), SAMPLE_FREQ_16KHZ, PICOOS_ENC_LIN)))```](https://github.com/robotology/speech/blob/master/svox-speech/speech.cpp#L356)
[```SAMPLE_FREQ_16KHZ, PICOOS_ENC_LIN);```](https://github.com/robotology/speech/blob/master/svox-speech/svoxpico/picosig.c#L938)
[```if (SAMPLE_FREQ_16KHZ != sdf->sf) { #L1555```](https://github.com/robotology/speech/blob/master/svox-speech/svoxpico/picoos.c#L1555)
[```if (SAMPLE_FREQ_16KHZ != sdf->sf) { #L1742```](https://github.com/robotology/speech/blob/master/svox-speech/svoxpico/picoos.c#L1742)

So, I was aiming to set up a frequency of 44,1KHz (44100), and I changed it in the first two files. It did compile, however when I was testing the "say "Hello, I am iCub" there was a segmentation fault in the yarpdev speech device. 
If I change it to 32KHz (32000), it does compile and it works. However, iCub speaks like a smurf (puffo :) 

I don't think it's related to the fact that an uint32...

I think it could be interested to take a look at ```sdf->sf``` as it has ```picoos_sd_file_t * ```

Any idea on how we could work this out?
