### ISSUE TITLE
Word timing in sentence

### ISSUE THREAD

**Issue by dcam0050** [robotology/speech#16]
I was wondering if it's possible to compute word timings within a sentence passed to the  speech yarp device. The reason being I would like to create an "animated say" such that one could trigger behaviour when a certain part of a sentence is reached.

The approach I was thinking of is:

1. A command is issued to iSpeak or the yarpdev with a parameter to perform the text to speech in silent mode and return word timings

2. Behaviour is set to happen with a delay equivalent to the word in question and then a delayed behaviour is triggered at the same time a regular iSpeak command is triggered

As an aside I'm using svox-tts on Ubuntu at the moment.

**Comment by pattacini** [comment]
@dcam0050 as of now we do not have resources for such a request, but we can accept a PR 😉
