### ISSUE TITLE
RFModule failed to open

### ISSUE THREAD

**Issue by sockchinglow** [robotology/speech#3]
Upon installation of the speech components with VS2010 and cmake v3.2.1, there were no errors in the make and build process. However, when running the ```speechRecognizer``` we receive the following error message:

```RFModule failed to open```

This comes just after ```rf``` configuration method is completed. Does anyone have any idea why this happens, and how we can resolve it?

**Comment by pattacini** [comment]
Hi @sockchinglow 

The message you saw should be printed as result of a failed configuration (see https://github.com/robotology/speech/blob/master/speechRecognizer/src/SpeechRecognizerModule.cpp#L155). However, the variable `everythingIsFine` does account for a quite large number of checks.

Therefore, could you please put some print-out in the `configure()` to catch which exact line sets `everythingIsFine=false`?

**Comment by vtikha** [comment]
Hi @sockchinglow, as a first step: are you running the `speechRecognizer` on a windows machine that is connected to the local network (if using the robot otherwise local server) and can ping/list the ports? (eg: that has access to the `yarp server`)

**Comment by maxime-petit** [comment]
Yop,

Make also sure that you have a recording device enable (either an external microphone or the embedded microphone on a laptop). The module fails to open if it is not pluggedin or disabled.

Just FYI also, if the recognition is not working, check that you have the proper english language ID loaded : 409 for english-US, 809 for english-UK for instance. 

./Max

**Comment by sockchinglow** [comment]
Max you're a genius! It was as simple as that; our mic was disabled.

**Comment by pattacini** [comment]
That's good.
:+1: for @maxime-petit
