### ISSUE TITLE
--noLegacy option as default in the ini file?

### ISSUE THREAD

**Issue by maxime-petit** [robotology/speech#4]
Yop,

I wanted to know if I can change the .ini file to have --noLegacy as default value when compiling the project. It is mandatory for the WYSIWYD project, but I am not sure if somebody else is using it.

Let me know

./Max

**Comment by pattacini** [comment]
Hi @maxime-petit 

Priority goes to our `IOL` demo, hence no modifications to default options.
`Wysiwyd` will rely on a different .ini file.

**Comment by pattacini** [comment]
You can for sure push here a new .ini file then.
