### ISSUE TITLE
svox-speech: yarpdev cannot find speech device 

### ISSUE THREAD

**Issue by apaikan** [robotology/speech#9]
The `CMakeLists.txt` from `svox-speech` needed to be modified to correctly create the speech device files (.so , .ini) 

For now, it creates a `lib` folder containing the library and `share/yarp/plugins` containing `speech.ini` in the build directory which is not visible for `yarpdev` or `yarp plugin --all`.

@drdanz  Would you please take a look at the cmake file to see it is coherent with our last modification on the yarp external plugins?

**Comment by pattacini** [comment]
Thanks a lot @apaikan for this addition.
@drdanz I'll take a look at the cmake problem.

**Comment by pattacini** [comment]
@robotology/wysiwyd-developers keep an eye here; once ready I'll let you know

**Comment by pattacini** [comment]
Solved thanks to the heavy support of @drdanz
